apiVersion: app/v1
kind: Application
metadata:
  name: app-of-apps
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/AlucardTheOne/AppInAppsCD
    targetRevision: main
    path: SpringApps
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  directory:
    recurse: true
