apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app2
  namespace: argocd
  annotation:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/AlucardTheOne/AppInAppsCD
    targetRevision: HEAD
    path: SpringApps/app2
  destination:
    server: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
