apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AlucardTheOne/AppInAppsCD
    targetRevision: HEAD
    path: SpringApps/app2
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
