apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: spring-boot-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
    namespace: istio-system
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "192.168.49.2"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: spring-boot-virtualservice2
  namespace: default
spec:
  gateways: 
    - spring-boot-gateway
  hosts:
  - "*"
  http:
  - route:
    - destination:
        host: 
          - "app1.192.168.49.2"
        port:
          number: 80
