apiVersion: app/v1
kind: Application
metadata:
  name: spring-boot-app
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/AlucardTheOne/AppInAppsCD
    targetRevision: HEAD
    path: SpringApps/app1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
